spring.datasource.url=${TEC_DATASOURCE_MYSQL_URL}
spring.datasource.username=${TEC_MYSQL_USER}
spring.datasource.password=${TEC_MYSQL_PASS}

#variable conexion mongo
spring.data.mongodb.uri=${TEC_DATASOURCE_MONGODB_URL}
spring.data.mongodb.database=${TEC_MONGODB_DB}

spring.ai.vectorstore.mongodb.collection-name=${TEC_MONGODB_COLLECTION}
spring.ai.vectorstore.mongodb.initialize-schema=true
spring.ai.vectorstore.mongodb.index-name=${TEC_MONGODB_INDEX}

#variables langchain
langchain4j.ollama.chat-model.base-url=${TEC_SERVER_OLLAMA_API}

#microfrontend chat
ec.com.technoloqie.chatbot.app.url=${TEC_CHATBOT_APP_URL}